### ISSUE TITLE
Cannot work in IOS

### ISSUE THREAD

**Issue by SevenNick** [JaimeCheng/wx-miniprogram-actionsheet#1]
The Component cannot work in my iphone X
Error message said that you can only use class selectors in Component

**Comment by JaimeCheng** [comment]
![image](https://user-images.githubusercontent.com/22406024/71810339-20716800-30ad-11ea-9323-3af547565e9a.png)
Sorry，I forgot it. You can open `wx-miniprogram-actionsheet/index.wxss` in line 22、23, and then add class for `button` 、`navigator`,then add the class in the page you used this component.
I'll update readme soon! Thanks for using!
